hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - +model=baseGNN
    - model.data_type=graph
    - model.num_layers=1,2
    - model.hidden_dim=32
    - dataset.pt_thr=null
    - train.epochs=20
    - train.scheduler=null
  job:
    name: __main__
    chdir: true
    override_dirname: +model=baseGNN,dataset.pt_thr=null,model.data_type=graph,model.hidden_dim=32,model.num_layers=1,2,train.epochs=20,train.scheduler=null
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.1
    version_base: '1.3'
    cwd: /mnt/workspace/graph_NN/neurograph
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /mnt/workspace/graph_NN/neurograph/neurograph/config
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      model: baseGNN
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
model:
  name: baseGNN
  n_classes: 2
  data_type: graph
  num_layers: 2
  layer_module: GCNConv
  hidden_dim: 32
  use_abs_weight: true
  use_weighted_edges: false
  final_node_dim: 32
  pooling: mean
  dropout: 0.2
  use_batchnorm: true
  num_heads: 2
  mlp_config:
    in_size: null
    out_size: null
    act_func: null
    act_func_params: null
    layers: []
seed: 1380
dataset:
  name: cobre
  data_type: graph
  experiment_type: fmri
  atlas: aal
  data_path: !!python/object/apply:pathlib.PosixPath
  - /
  - mnt
  - workspace
  - graph_NN
  - neurograph
  - datasets
  abs_thr: null
  pt_thr: null
  feature_type: conn_profile
train:
  device: cuda
  epochs: 20
  batch_size: 8
  valid_batch_size: 8
  optim: Adam
  optim_args:
    lr: 0.001
    weight_decay: 0.0001
  scheduler: null
  scheduler_metric: loss
  scheduler_args:
    factor: 0.1
    patience: 5
    verbose: true
  select_best_metric: loss
  loss: CrossEntropyLoss
  loss_args:
    reduction: sum
  prob_thr: 0.5
log:
  test_step: 1
  wandb_project: mri_gnn_2
  wandb_name: null
  wandb_mode: null
